#!/bin/bash

# Session Name
session="Qt"
SESSIONEXISTS=$(tmux list-sessions | grep $SESSION)

# Only create tmux session if it doesn't already exist
if [ "$SESSIONEXISTS" = "" ]
then
    tmux new-session -d -s $session
    tmux rename-window -t 0 'Main'

    # start up main window
    tmux send-keys -t 'Main' 'cd /home/johannes/fh/GPS_Logbook/GPS_Logbook' C-m 'clear' C-m

    # Create and setup pane for ssh to pi
    tmux new-window -t $session:2 -n 'pi ssh'
    tmux send-keys -t 'pi ssh' 'ssh g' C-m


    tmux split-window -h -p 30

fi


# Attach Session, on the Main window
tmux attach-session -t $session:1
